[profile.default]
src = "contracts"
out = "out"
script = "scripts"
libs = [ "node_modules" ]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[profile.default.rpc_endpoints]
baseTestnet = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

[profile.default.lint]
lint_on_build = false
